/*
 * This file was automatically generated by EvoSuite
 * Tue Dec 03 17:14:02 GMT 2019
 */

package ajaxrequest;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ajaxrequest.Panel;
import javax.faces.context.FacesContext;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Panel_ESTest extends Panel_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Panel panel0 = new Panel();
      // Undeclared exception!
      try { 
        panel0.encodeBegin((FacesContext) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("javax.faces.component.UIComponentBase", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Panel panel0 = new Panel();
      // Undeclared exception!
      try { 
        panel0.decode((FacesContext) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("javax.faces.component.UIComponentBase", e);
      }
  }
}
