/*
 * This file was automatically generated by EvoSuite
 * Tue Dec 03 17:24:06 GMT 2019
 */

package ajaxqueue;

import org.junit.Test;
import static org.junit.Assert.*;
import ajaxqueue.QueueBean;
import javax.faces.event.ActionEvent;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class QueueBean_ESTest extends QueueBean_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      QueueBean queueBean0 = new QueueBean();
      queueBean0.process((ActionEvent) null);
  }
}
