/*
 * This file was automatically generated by EvoSuite
 * Tue Dec 03 17:12:24 GMT 2019
 */

package ajaxrequest;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ajaxrequest.Bean;
import javax.faces.component.UICommand;
import javax.faces.component.UIMessages;
import javax.faces.component.UISelectOne;
import javax.faces.event.ActionEvent;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Bean_ESTest extends Bean_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Bean bean0 = new Bean();
      bean0.setFireOptions("4$f!j");
      String string0 = bean0.getFireOptions();
      assertEquals("4$f!j", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Bean bean0 = new Bean();
      UISelectOne uISelectOne0 = new UISelectOne();
      ActionEvent actionEvent0 = new ActionEvent(uISelectOne0);
      // Undeclared exception!
      try { 
        bean0.reset(actionEvent0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ajaxrequest.Bean", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Bean bean0 = new Bean();
      UIMessages uIMessages0 = new UIMessages();
      ActionEvent actionEvent0 = new ActionEvent(uIMessages0);
      // Undeclared exception!
      try { 
        bean0.getOptions(actionEvent0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // javax.faces.component.UIMessages cannot be cast to javax.faces.component.UICommand
         //
         verifyException("ajaxrequest.Bean", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Bean bean0 = new Bean();
      String string0 = bean0.getFireOptions();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Bean bean0 = new Bean();
      bean0.setFireOptions("");
      String string0 = bean0.getFireOptions();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      UICommand uICommand0 = new UICommand();
      Bean bean0 = new Bean();
      ActionEvent actionEvent0 = new ActionEvent(uICommand0);
      // Undeclared exception!
      try { 
        bean0.getOptions(actionEvent0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ajaxrequest.Bean", e);
      }
  }
}
