/*
 * This file was automatically generated by EvoSuite
 * Tue Dec 03 17:36:07 GMT 2019
 */

package guessnumber;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import guessnumber.ClientSideValidatorHandler;
import javax.faces.event.ComponentSystemEvent;
import javax.faces.view.facelets.FaceletHandler;
import javax.faces.view.facelets.Tag;
import javax.faces.view.facelets.ValidatorConfig;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ClientSideValidatorHandler_ESTest extends ClientSideValidatorHandler_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ClientSideValidatorHandler.PreRenderListener clientSideValidatorHandler_PreRenderListener0 = new ClientSideValidatorHandler.PreRenderListener();
      ComponentSystemEvent componentSystemEvent0 = mock(ComponentSystemEvent.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(componentSystemEvent0).getSource();
      // Undeclared exception!
      try { 
        clientSideValidatorHandler_PreRenderListener0.processEvent(componentSystemEvent0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("guessnumber.ClientSideValidatorHandler$PreRenderListener", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ValidatorConfig validatorConfig0 = mock(ValidatorConfig.class, new ViolatedAssumptionAnswer());
      doReturn((FaceletHandler) null).when(validatorConfig0).getNextHandler();
      doReturn((Tag) null).when(validatorConfig0).getTag();
      doReturn((String) null).when(validatorConfig0).getTagId();
      ClientSideValidatorHandler clientSideValidatorHandler0 = null;
      try {
        clientSideValidatorHandler0 = new ClientSideValidatorHandler(validatorConfig0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("javax.faces.view.facelets.TagHandler", e);
      }
  }
}
