/*
 * This file was automatically generated by EvoSuite
 * Tue Dec 03 17:10:46 GMT 2019
 */

package ajaxrequest;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ajaxrequest.RequestPhaseListener;
import javax.faces.event.PhaseEvent;
import javax.faces.event.PhaseId;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RequestPhaseListener_ESTest extends RequestPhaseListener_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RequestPhaseListener requestPhaseListener0 = new RequestPhaseListener();
      // Undeclared exception!
      try { 
        requestPhaseListener0.beforePhase((PhaseEvent) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ajaxrequest.RequestPhaseListener", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      RequestPhaseListener requestPhaseListener0 = new RequestPhaseListener();
      PhaseId phaseId0 = requestPhaseListener0.getPhaseId();
      assertNotNull(phaseId0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      RequestPhaseListener requestPhaseListener0 = new RequestPhaseListener();
      requestPhaseListener0.afterPhase((PhaseEvent) null);
  }
}
