/*
 * This file was automatically generated by EvoSuite
 * Tue Dec 03 17:19:26 GMT 2019
 */

package basicajax;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import basicajax.RedirectBean;
import javax.faces.event.ValueChangeEvent;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RedirectBean_ESTest extends RedirectBean_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RedirectBean redirectBean0 = new RedirectBean();
      ValueChangeEvent valueChangeEvent0 = mock(ValueChangeEvent.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        redirectBean0.redirectPage(valueChangeEvent0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("basicajax.RedirectBean", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      RedirectBean redirectBean0 = new RedirectBean();
      // Undeclared exception!
      try { 
        redirectBean0.redirect();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("basicajax.RedirectBean", e);
      }
  }
}
