/*
 * This file was automatically generated by EvoSuite
 * Wed Dec 04 21:19:38 GMT 2019
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AddTwoIntegers_ESTest extends AddTwoIntegers_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      int int0 = AddTwoIntegers.add(203, 1);
      assertEquals(204, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      int int0 = AddTwoIntegers.add(0, (-1968));
      assertEquals((-1968), int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      int int0 = AddTwoIntegers.add(0, 0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      String[] stringArray0 = new String[3];
      AddTwoIntegers.main(stringArray0);
      assertEquals(3, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      AddTwoIntegers addTwoIntegers0 = new AddTwoIntegers();
  }
}
