/*
 * This file was automatically generated by EvoSuite
 * Fri Dec 06 21:02:33 GMT 2019
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AddTwoIntegers_ESTest extends AddTwoIntegers_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      int int0 = AddTwoIntegers.add(0, 0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      int int0 = AddTwoIntegers.add(0, (-1340));
      assertEquals((-1340), int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      int int0 = AddTwoIntegers.add(539, 1358);
      assertEquals(1897, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      AddTwoIntegers.main((String[]) null);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      AddTwoIntegers addTwoIntegers0 = new AddTwoIntegers();
  }
}
