/*
 * This file was automatically generated by EvoSuite
 * Tue Dec 03 17:21:52 GMT 2019
 */

package basicajax;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import basicajax.DemoResourceBean;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.javaee.injection.Injector;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DemoResourceBean_ESTest extends DemoResourceBean_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DemoResourceBean.DemoSourceInfo demoResourceBean_DemoSourceInfo0 = new DemoResourceBean.DemoSourceInfo("F#lDhj2M9Xng>", "sc[A&~hC^S");
      assertEquals("F#lDhj2M9Xng>", demoResourceBean_DemoSourceInfo0.getLabel());
      assertEquals("sc[A&~hC^S", demoResourceBean_DemoSourceInfo0.getSourceFilePath());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LinkedList<DemoResourceBean.DemoSourceInfo> linkedList0 = new LinkedList<DemoResourceBean.DemoSourceInfo>();
      DemoResourceBean.DemoBean demoResourceBean_DemoBean0 = new DemoResourceBean.DemoBean("", "U++?U)f3=}C6ku", linkedList0);
      assertEquals("", demoResourceBean_DemoBean0.getDemoName());
      assertEquals("U++?U)f3=}C6ku", demoResourceBean_DemoBean0.getPage());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      DemoResourceBean demoResourceBean0 = new DemoResourceBean();
      demoResourceBean0.getDemoBeans();
      // Undeclared exception!
      try { 
        Injector.executePostConstruct((Object) demoResourceBean0, (Class<?>) DemoResourceBean.class);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Failed to execute @PostConstructor in basicajax.DemoResourceBean
         //
         verifyException("org.evosuite.runtime.javaee.injection.Injector", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      DemoResourceBean.DemoSourceInfo demoResourceBean_DemoSourceInfo0 = new DemoResourceBean.DemoSourceInfo("O{FLF 2fZfS(o", "O{FLF 2fZfS(o");
      String string0 = demoResourceBean_DemoSourceInfo0.getLabel();
      assertEquals("O{FLF 2fZfS(o", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      DemoResourceBean.DemoSourceInfo demoResourceBean_DemoSourceInfo0 = new DemoResourceBean.DemoSourceInfo("O{FLF 2fZfS(o", "O{FLF 2fZfS(o");
      String string0 = demoResourceBean_DemoSourceInfo0.getSourceFilePath();
      assertEquals("O{FLF 2fZfS(o", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      LinkedList<DemoResourceBean.DemoSourceInfo> linkedList0 = new LinkedList<DemoResourceBean.DemoSourceInfo>();
      DemoResourceBean.DemoBean demoResourceBean_DemoBean0 = new DemoResourceBean.DemoBean("O{FLF 2fZfS(o", "O{FLF 2fZfS(o", linkedList0);
      List<DemoResourceBean.DemoSourceInfo> list0 = demoResourceBean_DemoBean0.getSourceInfo();
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      LinkedList<DemoResourceBean.DemoSourceInfo> linkedList0 = new LinkedList<DemoResourceBean.DemoSourceInfo>();
      DemoResourceBean.DemoBean demoResourceBean_DemoBean0 = new DemoResourceBean.DemoBean("O{FLF 2fZfS(o", "O{FLF 2fZfS(o", linkedList0);
      String string0 = demoResourceBean_DemoBean0.getPage();
      assertEquals("O{FLF 2fZfS(o", string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      LinkedList<DemoResourceBean.DemoSourceInfo> linkedList0 = new LinkedList<DemoResourceBean.DemoSourceInfo>();
      DemoResourceBean.DemoBean demoResourceBean_DemoBean0 = new DemoResourceBean.DemoBean("O{FLF 2fZfS(o", "O{FLF 2fZfS(o", linkedList0);
      String string0 = demoResourceBean_DemoBean0.getDemoName();
      assertEquals("O{FLF 2fZfS(o", string0);
  }
}
