/*
 * This file was automatically generated by EvoSuite
 * Tue Dec 03 17:31:49 GMT 2019
 */

package customscope;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import customscope.Bean;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.javaee.injection.Injector;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Bean_ESTest extends Bean_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Bean bean0 = new Bean();
      // Undeclared exception!
      try { 
        Injector.executePostConstruct((Object) bean0, (Class<?>) Bean.class);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Failed to execute @PostConstructor in customscope.Bean
         //
         verifyException("org.evosuite.runtime.javaee.injection.Injector", e);
      }
  }
}
