/*
 * This file was automatically generated by EvoSuite
 * Tue Dec 03 17:29:04 GMT 2019
 */

package ezcomp;

import org.junit.Test;
import static org.junit.Assert.*;
import ezcomp.NumberHolder;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class NumberHolder_ESTest extends NumberHolder_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NumberHolder numberHolder0 = new NumberHolder();
      numberHolder0.setNumber((Integer) null);
      Integer integer0 = numberHolder0.getNumber();
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      NumberHolder numberHolder0 = new NumberHolder();
      Integer integer0 = new Integer(1);
      numberHolder0.setNumber(integer0);
      Integer integer1 = numberHolder0.getNumber();
      assertEquals(1, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      NumberHolder numberHolder0 = new NumberHolder();
      Integer integer0 = numberHolder0.getNumber();
      assertEquals(0, (int)integer0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      NumberHolder numberHolder0 = new NumberHolder();
      Integer integer0 = new Integer((-1));
      numberHolder0.setNumber(integer0);
      Integer integer1 = numberHolder0.getNumber();
      assertEquals((-1), (int)integer1);
  }
}
