/*
 * This file was automatically generated by EvoSuite
 * Fri Nov 22 21:23:24 GMT 2019
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class methods_ESTest extends methods_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      methods methods0 = new methods();
      int int0 = methods0.min((-716), (-1));
      assertEquals((-716), int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      methods methods0 = new methods();
      int int0 = methods0.min(0, 0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      methods methods0 = new methods();
      int int0 = methods0.min(2178, 2178);
      assertEquals(2178, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      methods methods0 = new methods();
      int int0 = methods0.min(0, (-1));
      assertEquals((-1), int0);
  }
}
