/*
 * This file was automatically generated by EvoSuite
 * Tue Dec 03 17:29:23 GMT 2019
 */

package ezcomp;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ezcomp.DemoResourceBean;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.javaee.injection.Injector;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DemoResourceBean_ESTest extends DemoResourceBean_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DemoResourceBean.DemoBean demoResourceBean_DemoBean0 = new DemoResourceBean.DemoBean("label", "%K2FT1an5%,oF", (List<DemoResourceBean.DemoSourceInfo>) null);
      assertEquals("label", demoResourceBean_DemoBean0.getDemoName());
      assertEquals("%K2FT1an5%,oF", demoResourceBean_DemoBean0.getPage());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DemoResourceBean demoResourceBean0 = new DemoResourceBean();
      demoResourceBean0.getDemoBeans();
      // Undeclared exception!
      try { 
        Injector.executePostConstruct((Object) demoResourceBean0, (Class<?>) DemoResourceBean.class);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Failed to execute @PostConstructor in ezcomp.DemoResourceBean
         //
         verifyException("org.evosuite.runtime.javaee.injection.Injector", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      DemoResourceBean.DemoSourceInfo demoResourceBean_DemoSourceInfo0 = new DemoResourceBean.DemoSourceInfo(">Fu", ">Fu");
      String string0 = demoResourceBean_DemoSourceInfo0.getSourceFilePath();
      assertEquals(">Fu", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      DemoResourceBean.DemoSourceInfo demoResourceBean_DemoSourceInfo0 = new DemoResourceBean.DemoSourceInfo(">Fu", ">Fu");
      String string0 = demoResourceBean_DemoSourceInfo0.getLabel();
      assertEquals(">Fu", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      LinkedList<DemoResourceBean.DemoSourceInfo> linkedList0 = new LinkedList<DemoResourceBean.DemoSourceInfo>();
      DemoResourceBean.DemoBean demoResourceBean_DemoBean0 = new DemoResourceBean.DemoBean(">Fu", ">Fu", linkedList0);
      String string0 = demoResourceBean_DemoBean0.getDemoName();
      assertEquals(">Fu", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      LinkedList<DemoResourceBean.DemoSourceInfo> linkedList0 = new LinkedList<DemoResourceBean.DemoSourceInfo>();
      DemoResourceBean.DemoBean demoResourceBean_DemoBean0 = new DemoResourceBean.DemoBean(">Fu", ">Fu", linkedList0);
      List<DemoResourceBean.DemoSourceInfo> list0 = demoResourceBean_DemoBean0.getSourceInfo();
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      LinkedList<DemoResourceBean.DemoSourceInfo> linkedList0 = new LinkedList<DemoResourceBean.DemoSourceInfo>();
      DemoResourceBean.DemoBean demoResourceBean_DemoBean0 = new DemoResourceBean.DemoBean(">Fu", ">Fu", linkedList0);
      String string0 = demoResourceBean_DemoBean0.getPage();
      assertEquals(">Fu", string0);
  }
}
