/*
 * This file was automatically generated by EvoSuite
 * Tue Dec 03 17:27:38 GMT 2019
 */

package ezcomp;

import org.junit.Test;
import static org.junit.Assert.*;
import ezcomp.InOutBean;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class InOutBean_ESTest extends InOutBean_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      InOutBean inOutBean0 = new InOutBean();
      inOutBean0.setValue((String) null);
      String string0 = inOutBean0.getValue();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      InOutBean inOutBean0 = new InOutBean();
      inOutBean0.setValue("");
      String string0 = inOutBean0.getValue();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      InOutBean inOutBean0 = new InOutBean();
      String string0 = inOutBean0.getValue();
      assertEquals("Hello World!", string0);
  }
}
